name: EMSwiftUI

settings:
    IPHONEOS_DEPLOYMENT_TARGET: '15.0'

options:
    bundleIdPrefix: com.aumetov
    indentWidth: 4
    tabWidth: 4
    groupSortPosition: top
        
configs:
    Debug: debug
    Release: release
    
packages:
    Factory:
        url: https://github.com/hmlongco/Factory.git
        majorVersion: 2.4.3
    Netify:
        url: https://github.com/aumetov7/Netify.git
        majorVersion: 1.1.0
    SwiftLintPlugins:
        url: https://github.com/SimplyDanny/SwiftLintPlugins
        majorVersion: 0.58.2
        
schemes:
    EMSwiftUI Debug:
        build:
            targets:
                EMSwiftUI: all
            run:
                config: Debug
            profile:
                config: Debug
            analyze:
                config: Debug
            archive:
                config: Debug
                revealArchiveInOrganizer: false
    EMSwiftUI Release:
        build:
            targets:
                EMSwiftUI: all
        run:
            config: Release
            gatherCoverageData: true
        profile:
            config: Release
        analyze:
            config: Release
        archive:
            config: Release
            revealArchiveInOrganizer: true
            
targets:
    EMSwiftUI:
        type: application
        platform: iOS
        deploymentTarget: "15.0"
        settings:
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1.0
            INFOPLIST_FILE: "EMSwiftUI/Core/Info.plist"
            ENABLE_USER_SCRIPT_SANDBOXING: YES
            ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        sources:
            - EMSwiftUI
        dependencies:
            - package: Factory
            - package: Netify
        buildToolPlugins:
            - plugin: SwiftLintBuildToolPlugin
              package: SwiftLintPlugins
